### PR TITLE
PR net connections

### PR DESCRIPTION
**Pull request by BlueSideStrongSide**
PR:
Extend the logic in the identified function to return a more inclusive list of the network connections.

- Current implementation only returns if the raddr and laddr are TRUE
- Target "representation" is essentially how windows shows the connections when viewing netstat.

Comparing the captured output of this tool versus a standard netstat -noa, shows a large list of network connections were missing from the log. We simply provide a new variable for temporary validation and write strings to represent the connection. Given the moment in time processing, it would be helpful to have a more complete list even if currently "no one" is connected to the network service.

### CODE REVIEW

**Comment by BlueSideStrongSide** [comment]
Hopefully I did this right :) thanks again

**Comment by chrisdoman** [comment]
Thank-you @BlueSideStrongSide and apologies for the delay.

One last thing before I hit merge- Do you agree to the contributor license agreement @ https://github.com/cado-security/varc/blob/main/Contributing.md? A simple "Yes" is sufficient.
Apologies for the extra step there, as we've licensed this under GPL we have to confirm we have permission to use any contributions explicitly.

**Comment by BlueSideStrongSide** [comment]
> Thank-you @BlueSideStrongSide and apologies for the delay.
> 
> One last thing before I hit merge- Do you agree to the contributor license agreement @ https://github.com/cado-security/varc/blob/main/Contributing.md? A simple "Yes" is sufficient. Apologies for the extra step there, as we've licensed this under GPL we have to confirm we have permission to use any contributions explicitly.

Yes you have my permission

No worries, first time seeing this done so cool to watch the legal part get handled.

**Review by chrisdoman — APPROVED** [review]
Thanks!

**Comment by chrisdoman** [comment]
@BlueSideStrongSide this is merged now, thanks again for this addition!

I'll update the pip library and binaries on the releases tab shortly to reflect this addition.

**Pull request merged**
